inherit: job:///strati/kitt/kitt-build-assets:looper/docker.yml

flows:
  build:
    try:
      - echo "Running my custom looper build flow."
      - shell: npm install -g rdme
      - shell: rdme openapi syncWithGithub.yaml --dryRun
      - call: buildDocker
